#!/usr/bin/env bash
# a bash script that transfer a file by SSH to a server
if [[ $# -lt 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1 
fi
if [[ $# == 3 ]]
then
	scp -o "StrictHostKeyChecking no" "${1}" "${3}@${2}":~/
	exit 1 
fi
if [[ $# == 4 ]]
then
	scp -i "${4}" -o "StrictHostKeyChecking no" "${1}" "${3}@${2}":~/
	exit 1 
fi
