#!/usr/bin/env bash
# a bash script that install nginx in a server
sudo apt update
sudo apt -y install nginx
sudo chmod 666 /var/www/html/index.nginx-debian.html
sudo chmod 666 /usr/share/nginx/html/index.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Hello World!" > /usr/share/nginx/html/index.html
sudo service nginx restart
