#!/usr/bin/env bash
# a bash script that install nginx in a server
sudo apt update
sudo apt -y install nginx
sudo chmod 666 /var/www/html/index.nginx-debian.html
sudo chmod 666 /usr/share/nginx/html/index.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Hello World!" > /usr/share/nginx/html/index.html
sed -i  's/# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000/rewrite \/redirect_me\/  https:\/\/www.youtube.com\/shorts\/g_mSpVVLjvo permanent;/' /etc/nginx/sites-available/default
