#!/usr/bin/env bash
# a bash script that creates a file, displays To infinity and beyond, I hate the kill command, Y U no love me?! and deletes the file /var/run/myscript.pid on the screen
a=0
echo $BASHPID > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit 0;' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit 0;' SIGQUIT
while [ $a ]; 
do
    echo 'To infinity and beyond'
    sleep 2
done;
