#!/usr/bin/env bash
# a bash script that creates a file, displays To infinity and beyond, I hate the kill command, Y U no love me?! and deletes the file /var/run/myscript.pid on the screen
echo $$ | sudo tee /var/run/holbertonscript.pid > /dev/null
trap "sudo rm /var/run/holbertonscript.pid;echo 'I hate the kill command';exit" SIGTERM
trap "sudo rm /var/run/holbertonscript.pid;echo 'I hate the kill command';exit" SIGQUIT
trap "echo 'Y U no love me?!'; exit" SIGINT
while ((1)); 
do
    echo 'To infinity and beyond'
    sleep 2
done
