#!/usr/bin/env bash
#a bash script that displays Best School 10 times, 4 is bad luck, 8 is good using if and elif

a=0

while ((a < 10))
do
	((a++))
	if ((a == 4))
	then
		echo "bad luck"
	elif ((a == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
