#!/usr/bin/env bash
# a bash script that configure nginx to fit some requirement
pkill -f apache2
sed -i s/80/8080/g /etc/nginx/sites-available/default
chmod 666 /etc/nginx/nginx.conf
sudo -su nginx nginx -c /etc/nginx/nginx.conf
